### ISSUE TITLE
Redis cluster support

### ISSUE THREAD

**Issue by lamvak** [voidfiles/lark#2]
Do you plan supporting Redis Cluster?
That would be a great feature. And a good use of REST style.

**Comment by voidfiles** [comment]
So, I see Lark as an external interface to redis, or redis setup in a cluster.

How do see lark fitting into redis cluster?

**Comment by lamvak** [comment]
I haven't (yet) used Redis cluster, so for now that's just my untested idea.
Lark as a middleware might allow a proxy / load balancer without client code being aware. Also might take care of redis cluster redirection in case key is present on a different shard.
That could (almost) mean one interface to both Redis and Redis cluster from Python.

**Comment by voidfiles** [comment]
Well, I wouldn't discount anything at this point, but I don't think this project would be a good place to try that.
